### ISSUE TITLE
String length is wrong for UTF

### ISSUE THREAD

**Issue by skx** [MelloTonio/Mellang#2]
The `len` built-in shows the wrong result for non-ASCII strings.

For example:

 ```
>> plsShow( len( "狐犬" ) );
```

**Comment by skx** [comment]
Simple patch would look like this:

[fix.txt](https://github.com/MelloTonio/Mellang/files/5885657/fix.txt)

**Comment by MelloTonio** [comment]
Fixed! Thanks!
